package de.chojo.xivapi.entities.item.sub;

import com.fasterxml.jackson.annotation.JsonProperty;

public record BaseParam(
        @JsonProperty("Head%") int head,
        @JsonProperty("MeldParam1") int meldParam1,
        @JsonProperty("ChestLegsFeet%") int chestLegsFeet,
        @JsonProperty("MeldParam2") int meldParam2,
        @JsonProperty("MeldParam3") int meldParam3,
        @JsonProperty("Description") String description,
        @JsonProperty("MeldParam4") int meldParam4,
        @JsonProperty("OrderPriority") int orderPriority,
        @JsonProperty("ChestHead%") int chestHead,
        @JsonProperty("Hands%") int hands,
        @JsonProperty("MeldParam0") int meldParam0,
        @JsonProperty("Description_ja") String descriptionJa,
        @JsonProperty("MeldParam9") int meldParam9,
        @JsonProperty("MeldParam5") int meldParam5,
        @JsonProperty("MeldParam6") int meldParam6,
        @JsonProperty("MeldParam7") int meldParam7,
        @JsonProperty("Name_de") String nameDe,
        @JsonProperty("MeldParam8") int meldParam8,
        @JsonProperty("Name") String name,
        @JsonProperty("Name_ja") String nameJa,
        @JsonProperty("Earring%") int earring,
        @JsonProperty("ChestHeadLegsFeet%") int chestHeadLegsFeet,
        @JsonProperty("ChestLegsGloves%") int chestLegsGloves,
        @JsonProperty("MeldParam10") int meldParam10,
        @JsonProperty("Chest%") int chest,
        @JsonProperty("MeldParam11") int meldParam11,
        @JsonProperty("1HWpn%") int jsonMember1HWpn,
        @JsonProperty("MeldParam12") int meldParam12,
        @JsonProperty("ID") int id,
        @JsonProperty("Description_en") String descriptionEn,
        @JsonProperty("Feet%") int feet,
        @JsonProperty("Legs%") int legs,
        @JsonProperty("Necklace%") int necklace,
        @JsonProperty("Ring%") int ring,
        @JsonProperty("LegsFeet%") int legsFeet,
        @JsonProperty("Bracelet%") int bracelet,
        @JsonProperty("UnderArmor%") int underArmor,
        @JsonProperty("Name_en") String nameEn,
        @JsonProperty("PacketIndex") int packetIndex,
        @JsonProperty("OH%") int oH,
        @JsonProperty("2HWpn%") int jsonMember2HWpn,
        @JsonProperty("Description_de") String descriptionDe,
        @JsonProperty("Waist%") int waist,
        @JsonProperty("HeadChestHandsLegsFeet%") int headChestHandsLegsFeet,
        @JsonProperty("Name_fr") String nameFr,
        @JsonProperty("Description_fr") String descriptionFr
) {
}
