package de.chojo.xivapi.entities.item.sub;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ClassJobCategory(
        @JsonProperty("CRP") int cRP,
        @JsonProperty("LNC") int lNC,
        @JsonProperty("BLM") int bLM,
        @JsonProperty("PLD") int pLD,
        @JsonProperty("WAR") int wAR,
        @JsonProperty("BLU") int bLU,
        @JsonProperty("MNK") int mNK,
        @JsonProperty("LTW") int lTW,
        @JsonProperty("Name_de") String nameDe,
        @JsonProperty("Name") String name,
        @JsonProperty("Name_ja") String nameJa,
        @JsonProperty("WVR") int wVR,
        @JsonProperty("ADV") int aDV,
        @JsonProperty("RPR") int rPR,
        @JsonProperty("THM") int tHM,
        @JsonProperty("FSH") int fSH,
        @JsonProperty("RDM") int rDM,
        @JsonProperty("CUL") int cUL,
        @JsonProperty("ID") int id,
        @JsonProperty("BSM") int bSM,
        @JsonProperty("WHM") int wHM,
        @JsonProperty("GSM") int gSM,
        @JsonProperty("AST") int aST,
        @JsonProperty("Name_en") String nameEn,
        @JsonProperty("ROG") int rOG,
        @JsonProperty("ACN") int aCN,
        @JsonProperty("SGE") int sGE,
        @JsonProperty("ARC") int aRC,
        @JsonProperty("NIN") int nIN,
        @JsonProperty("MCH") int mCH,
        @JsonProperty("MIN") int mIN,
        @JsonProperty("PGL") int pGL,
        @JsonProperty("BRD") int bRD,
        @JsonProperty("SMN") int sMN,
        @JsonProperty("ALC") int aLC,
        @JsonProperty("DNC") int dNC,
        @JsonProperty("DRG") int dRG,
        @JsonProperty("SCH") int sCH,
        @JsonProperty("GNB") int gNB,
        @JsonProperty("Name_fr") String nameFr,
        @JsonProperty("ARM") int aRM,
        @JsonProperty("DRK") int dRK,
        @JsonProperty("BTN") int bTN,
        @JsonProperty("GLA") int gLA,
        @JsonProperty("CNJ") int cNJ,
        @JsonProperty("MRD") int mRD,
        @JsonProperty("SAM") int sAM
) {
}
