package de.chojo.xivapi.entities.item.sub.classjobrepair;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.chojo.xivapi.entities.item.ActionCategory;
import de.chojo.xivapi.entities.item.ActionTimelineHit;
import de.chojo.xivapi.entities.item.AnimationEnd;
import de.chojo.xivapi.entities.item.AnimationStart;
import de.chojo.xivapi.entities.item.AttackType;
import de.chojo.xivapi.entities.item.VFX;
import de.chojo.xivapi.entities.item.sub.ClassJobCategory;

public record LimitBreak(
        @JsonProperty("AttackTypeTargetID") int attackTypeTargetID,
        @JsonProperty("AnimationStart") AnimationStart animationStart,
        @JsonProperty("Omen") Object omen,
        @JsonProperty("ActionComboTargetID") int actionComboTargetID,
        @JsonProperty("AnimationEndTarget") String animationEndTarget,
        @JsonProperty("StatusGainSelf") Object statusGainSelf,
        @JsonProperty("Aspect") int aspect,
        @JsonProperty("MaxCharges") int maxCharges,
        @JsonProperty("Name") String name,
        @JsonProperty("SecondaryCostType") int secondaryCostType,
        @JsonProperty("ActionCategory") ActionCategory actionCategory,
        @JsonProperty("ClassJobCategory") ClassJobCategory classJobCategory,
        @JsonProperty("Name_ja") String nameJa,
        @JsonProperty("AnimationStartTargetID") int animationStartTargetID,
        @JsonProperty("AnimationEnd") AnimationEnd animationEnd,
        @JsonProperty("AnimationStartTarget") String animationStartTarget,
        @JsonProperty("TargetArea") int targetArea,
        @JsonProperty("CooldownGroup") int cooldownGroup,
        @JsonProperty("ActionCombo") Object actionCombo,
        @JsonProperty("ClassJobLevel") int classJobLevel,
        @JsonProperty("ID") int id,
        @JsonProperty("ActionTimelineHit") ActionTimelineHit actionTimelineHit,
        @JsonProperty("BehaviourType") int behaviourType,
        @JsonProperty("EffectRange") int effectRange,
        @JsonProperty("OmenTargetID") int omenTargetID,
        @JsonProperty("VFX") VFX vFX,
        @JsonProperty("AttackType") AttackType attackType,
        @JsonProperty("Range") int range,
        @JsonProperty("Recast100ms") int recast100ms,
        @JsonProperty("ActionTimelineHitTarget") String actionTimelineHitTarget,
        @JsonProperty("ClassJobCategoryTarget") String classJobCategoryTarget,
        @JsonProperty("StatusGainSelfTargetID") int statusGainSelfTargetID,
        @JsonProperty("SecondaryCostValue") int secondaryCostValue,
        @JsonProperty("Cast100ms") int cast100ms,
        @JsonProperty("Icon") String icon,
        @JsonProperty("Name_fr") String nameFr,
        @JsonProperty("CanTargetFriendly") int canTargetFriendly,
        @JsonProperty("ActionCategoryTarget") String actionCategoryTarget,
        @JsonProperty("ActionProcStatusTargetID") int actionProcStatusTargetID,
        @JsonProperty("ActionCategoryTargetID") int actionCategoryTargetID,
        @JsonProperty("VFXTargetID") int vFXTargetID,
        @JsonProperty("ClassJobTargetID") int classJobTargetID,
        @JsonProperty("ClassJobCategoryTargetID") int classJobCategoryTargetID,
        @JsonProperty("IsRoleAction") int isRoleAction,
        @JsonProperty("CastType") int castType,
        @JsonProperty("IconID") int iconID,
        @JsonProperty("Name_de") String nameDe,
        @JsonProperty("VFXTarget") String vFXTarget,
        @JsonProperty("CanTargetDead") int canTargetDead,
        @JsonProperty("StatusGainSelfTarget") String statusGainSelfTarget,
        @JsonProperty("CanTargetHostile") int canTargetHostile,
        @JsonProperty("AnimationEndTargetID") int animationEndTargetID,
        @JsonProperty("CanTargetParty") int canTargetParty,
        @JsonProperty("IsPlayerAction") int isPlayerAction,
        @JsonProperty("ActionComboTarget") String actionComboTarget,
        @JsonProperty("ClassJob") Object classJob,
        @JsonProperty("IsPvP") int isPvP,
        @JsonProperty("PrimaryCostType") int primaryCostType,
        @JsonProperty("PrimaryCostValue") int primaryCostValue,
        @JsonProperty("AttackTypeTarget") String attackTypeTarget,
        @JsonProperty("ActionTimelineHitTargetID") int actionTimelineHitTargetID,
        @JsonProperty("AffectsPosition") int affectsPosition,
        @JsonProperty("Name_en") String nameEn,
        @JsonProperty("ActionProcStatus") Object actionProcStatus,
        @JsonProperty("PreservesCombo") int preservesCombo,
        @JsonProperty("UnlockLink") int unlockLink,
        @JsonProperty("OmenTarget") String omenTarget,
        @JsonProperty("IconHD") String iconHD,
        @JsonProperty("XAxisModifier") int xAxisModifier,
        @JsonProperty("ActionProcStatusTarget") String actionProcStatusTarget,
        @JsonProperty("AdditionalCooldownGroup") int additionalCooldownGroup,
        @JsonProperty("ClassJobTarget") String classJobTarget,
        @JsonProperty("CanTargetSelf") int canTargetSelf
) {
}
