package de.chojo.xivapi.entities.action;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.chojo.xivapi.entities.action.sub.ActionCategory;
import de.chojo.xivapi.entities.action.sub.ActionTimelineHit;
import de.chojo.xivapi.entities.action.sub.AnimationEnd;
import de.chojo.xivapi.entities.action.sub.AnimationStart;
import de.chojo.xivapi.entities.action.sub.AttackType;
import de.chojo.xivapi.entities.shared.GamePatch;
import de.chojo.xivapi.entities.action.sub.Omen;
import de.chojo.xivapi.entities.action.sub.VFX;

import java.util.List;

public record Action(@JsonProperty("ActionCategory") ActionCategory actionCategory,
                     @JsonProperty("ActionCategoryTarget") String actionCategoryTarget,
                     @JsonProperty("ActionCategoryTargetID") int actionCategoryTargetId,
                     @JsonProperty("ActionCombo") String actionCombo,
                     @JsonProperty("ActionComboTarget") String actionComboTarget,
                     @JsonProperty("ActionComboTargetID") int actionComboTargetId,
                     @JsonProperty("ActionProcStatus") String actionProcStatus,
                     @JsonProperty("ActionProcStatusTarget") String actionProcStatusTarget,
                     @JsonProperty("ActionProcStatusTargetID") int actionProcStatusTargetId,
                     @JsonProperty("ActionTimelineHit") ActionTimelineHit actionTimelineHit,
                     @JsonProperty("ActionTimelineHitTarget") String actionTimelineHitTarget,
                     @JsonProperty("ActionTimelineHitTargetID") int actionTimelineHitTargetId,
                     @JsonProperty("AdditionalCooldownGroup") int additionalCooldownGroup,
                     @JsonProperty("AffectsPosition") int affectsPosition,
                     @JsonProperty("AnimationEnd") AnimationEnd animationEnd,
                     @JsonProperty("AnimationEndTarget") String animationEndTarget,
                     @JsonProperty("AnimationEndTargetID") int animationEndTargetId,
                     @JsonProperty("AnimationStart") AnimationStart animationStart,
                     @JsonProperty("AnimationStartTarget") String animationStartTarget,
                     @JsonProperty("AnimationStartTargetID") int animationStartTargetId,
                     @JsonProperty("Aspect") int aspect,
                     @JsonProperty("AttackType") AttackType attackType,
                     @JsonProperty("AttackTypeTarget") String attackTypeTarget,
                     @JsonProperty("AttackTypeTargetID") int AttackTypeTargetId,
                     @JsonProperty("BehaviourType") int behaviourType,
                     @JsonProperty("CanTargetDead") int canTargetDead,
                     @JsonProperty("CanTargetFriendly") int canTargetFriendly,
                     @JsonProperty("CanTargetHostile") int canTargetHostile,
                     @JsonProperty("CanTargetParty") int canTargetParty,
                     @JsonProperty("CanTargetSelf") int canTargetSelf,
                     @JsonProperty("Cast100ms") int cast100Ms,
                     @JsonProperty("CastType") int castType,
                     @JsonProperty("ClassJob") String classJob,
                     @JsonProperty("ClassJobCategory") String classJobCategory,
                     @JsonProperty("ClassJobCategoryTarget") String classJobCategoryTarget,
                     @JsonProperty("ClassJobCategoryTargetID") int classJobCategoryTargetId,
                     @JsonProperty("ClassJobLevel") int classJobLevel,
                     @JsonProperty("ClassJobTarget") String classJobTarget,
                     @JsonProperty("ClassJobTargetID") String classJobTargetId,
                     @JsonProperty("CooldownGroup") int cooldownGroup,
                     @JsonProperty("Description") String description,
                     @JsonProperty("DescriptionJSON_cn") String descriptionJSONCn,
                     @JsonProperty("DescriptionJSON_kr") String descriptionJSONKr,
                     @JsonProperty("Description_cn") String descriptionCn,
                     @JsonProperty("Description_de") String descriptionDe,
                     @JsonProperty("Description_en") String descriptionEn,
                     @JsonProperty("Description_fr") String descriptionFr,
                     @JsonProperty("Description_ja") String descriptionJa,
                     @JsonProperty("Description_kr") String descriptionKr,
                     @JsonProperty("EffectRange") int effectRange,
                     @JsonProperty("<") List<String> gameContentLinks,
                     @JsonProperty("GamePatch") GamePatch gamePatch,
                     @JsonProperty("ID") int id,
                     @JsonProperty("Icon") String icon,
                     @JsonProperty("IconHD") String iconHD,
                     @JsonProperty("IconID") int iconId,
                     @JsonProperty("IsPlayerAction") int isPlayerAction,
                     @JsonProperty("IsPvP") int isPvP,
                     @JsonProperty("IsRoleAction") int isRoleAction,
                     @JsonProperty("MaxCharges") int maxCharges,
                     @JsonProperty("Name") String name,
                     @JsonProperty("Name_de") String nameDe,
                     @JsonProperty("Name_en") String nameEn,
                     @JsonProperty("Name_fr") String nameFr,
                     @JsonProperty("Name_ja") String nameJa,
                     @JsonProperty("Omen") Omen omen,
                     @JsonProperty("OmenTarget") String omenTarget,
                     @JsonProperty("OmenTargetID") int omenTargetId,
                     @JsonProperty("Patch") int patch,
                     @JsonProperty("PreservesCombo") int preservesCombo,
                     @JsonProperty("PrimaryCostType") int primaryCostType,
                     @JsonProperty("PrimaryCostValue") int primaryCostValue,
                     @JsonProperty("Range") int range,
                     @JsonProperty("Recast100ms") int recast100Ms,
                     @JsonProperty("SecondaryCostType") int secondaryCostType,
                     @JsonProperty("SecondaryCostValue") int secondaryCostValue,
                     @JsonProperty("StatusGainSelf") String statusGainSelf,
                     @JsonProperty("StatusGainSelfTarget") String statusGainSelfTarget,
                     @JsonProperty("StatusGainSelfTargetID") int statusGainSelfTargetId,
                     @JsonProperty("TargetArea") int targetArea,
                     @JsonProperty("UnlockLink") int unlockLink,
                     @JsonProperty("Url") String url,
                     @JsonProperty("VFX") VFX vfx,
                     @JsonProperty("VFXTarget") String vfxTarget,
                     @JsonProperty("VFXTargetID") int vfxTargetId,
                     @JsonProperty("XAxisModifier") int xAxisModifier) {

}
